// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNqML6WfIMl3zUCqMhjgQ_0w89c7PAzSE',
    appId: '1:361924353272:web:e527a6e2aab9876677ef0d',
    messagingSenderId: '361924353272',
    projectId: 'sd-task-a6101',
    authDomain: 'sd-task-a6101.firebaseapp.com',
    storageBucket: 'sd-task-a6101.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRExZ_hhvTosg3rqVHdkJ3fpataX7Sagc',
    appId: '1:361924353272:android:ac2c32097c24116a77ef0d',
    messagingSenderId: '361924353272',
    projectId: 'sd-task-a6101',
    storageBucket: 'sd-task-a6101.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEqFaxccqx6BntjEDYOxNi66Flgi1l04o',
    appId: '1:361924353272:ios:e187c17159db88ca77ef0d',
    messagingSenderId: '361924353272',
    projectId: 'sd-task-a6101',
    storageBucket: 'sd-task-a6101.appspot.com',
    iosBundleId: 'com.example.sdTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEqFaxccqx6BntjEDYOxNi66Flgi1l04o',
    appId: '1:361924353272:ios:42bd7d54854f2be877ef0d',
    messagingSenderId: '361924353272',
    projectId: 'sd-task-a6101',
    storageBucket: 'sd-task-a6101.appspot.com',
    iosBundleId: 'com.example.sdTask.RunnerTests',
  );
}
